export const product =[
    {
        "id":"a001",
        "color":"太空灰",
        "storage":"64GB",
        "network":"Wi-Fi",
        "price":19900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/appleair-gray.jpg"
    },
    {
        "id":"a002",
        "color":"藍",
        "storage":"64GB",
        "network":"Wi-Fi",
        "price":19900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-blue.jpg"
    },
    {
        "id":"a003",
        "color":"粉紅",
        "storage":"64GB",
        "network":"Wi-Fi",
        "price":19900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-pink.jpg"
    },
    {
        "id":"a004",
        "color":"紫",
        "storage":"64GB",
        "network":"Wi-Fi",
        "price":19900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-purple.jpg"
    },
    {
        "id":"a005",
        "color":"星空",
        "storage":"64GB",
        "network":"Wi-Fi",
        "price":19900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-star.jpg"
    },
    {
        "id":"a006",
        "color":"太空灰",
        "storage":"256GB",
        "network":"Wi-Fi",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/appleair-gray.jpg"
    },
    {
        "id":"a007",
        "color":"藍",
        "storage":"256GB",
        "network":"Wi-Fi",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-blue.jpg"
    },
    {
        "id":"a008",
        "color":"粉紅",
        "storage":"256GB",
        "network":"Wi-Fi",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-pink.jpg"
    },
    {
        "id":"a009",
        "color":"紫",
        "storage":"256GB",
        "network":"Wi-Fi",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-purple.jpg"
    },
    {
        "id":"a010",
        "color":"星空",
        "storage":"256GB",
        "network":"Wi-Fi",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-star.jpg"
    },
    {
        "id":"a011",
        "color":"太空灰",
        "storage":"256GB",
        "network":"Wi-Fi+network",
        "price":29900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/appleair-gray.jpg"
    },
    {
        "id":"a012",
        "color":"藍",
        "storage":"256GB",
        "network":"Wi-Fi+network",
        "price":29900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-blue.jpg"
    },
    {
        "id":"a013",
        "color":"粉紅",
        "storage":"256GB",
        "network":"Wi-Fi+network",
        "price":29900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-pink.jpg"
    },
    {
        "id":"a014",
        "color":"紫",
        "storage":"256GB",
        "network":"Wi-Fi+network",
        "price":29900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-purple.jpg"
    },
    {
        "id":"a015",
        "color":"星空",
        "storage":"256GB",
        "network":"Wi-Fi+network",
        "price":29900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-star.jpg"
    },
    {
        "id":"a016",
        "color":"太空灰",
        "storage":"64GB",
        "network":"Wi-Fi+network",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/appleair-gray.jpg"
    },
    {
        "id":"a017",
        "color":"藍",
        "storage":"64GB",
        "network":"Wi-Fi+network",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-blue.jpg"
    },
    {
        "id":"a018",
        "color":"粉紅",
        "storage":"64GB",
        "network":"Wi-Fi+network",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-pink.jpg"
    },
    {
        "id":"a019",
        "color":"紫",
        "storage":"64GB",
        "network":"Wi-Fi+network",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-purple.jpg"
    },
    {
        "id":"a020",
        "color":"星空",
        "storage":"64GB",
        "network":"Wi-Fi+network",
        "price":24900,
        "picture":"https://raw.githubusercontent.com/b10802064/filestorge/main/ipadair-star.jpg"
    }
]